Repository classvar/classvar-user-frontend, pull requests merged in 2021-08, with the labels that each got.

#28 Create Proctor template
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/App.tsx~Stashed changes
  src/common/router.type.ts
  src/components/templates/Proctor/Proctor.style.ts
  src/components/templates/Proctor/Proctor.tsx
  src/components/templates/Proctor/index.ts
  src/index.css
  src/index.tsx
  src/lib/styles/styled.d.ts
  src/lib/styles/theme.ts
  src/logo.svg
  src/pages/Login/Login.tsx
  src/pages/Routes.tsx
  tsconfig.extend.json
Labels: feature

#26 Create Indicator
  src/components/atoms/Indicator/Index.ts
  src/components/atoms/Indicator/Indicator.style.ts
  src/components/atoms/Indicator/Indicator.tsx
  src/components/atoms/Indicator/Indicator.type.ts
Labels: feature

#31 Create Table
  package.json
  src/components/atoms/Checkbox/Checkbox.tsx
  src/components/atoms/Checkbox/Checkbox.type.ts
  src/components/atoms/Checkbox/index.ts
  src/components/atoms/Table/Table.style.ts
  src/components/atoms/Table/Table.tsx
  src/components/atoms/Table/Table.type.ts
  src/components/atoms/Table/index.ts
  src/types/react-table-config.d.ts
  yarn.lock
Labels: feature

#32 Create Home page
  src/components/atoms/Indicator/Index.ts
  src/components/atoms/SidebarFrame/SidebarFrame.style.ts
  src/components/organisms/Headerbar/Headerbar.style.ts
  src/components/organisms/Headerbar/Headerbar.tsx
  src/components/templates/Proctor/Proctor.style.ts
  src/components/templates/Proctor/Proctor.tsx
  src/pages/Exam/Exam.style.ts
  src/pages/Exam/Exam.tsx
  src/pages/Exam/dummydata.ts
  src/pages/Exam/index.ts
Labels: feature

#34 Add index.ts in Indicator
  src/components/atoms/Indicator/index.ts
  src/pages/Exam/Exam.tsx
Labels: feature

#35 Change Modal design
  src/components/atoms/Button/Button.style.ts
  src/components/atoms/Button/Button.tsx
  src/components/atoms/Button/Button.type.ts
  src/components/organisms/Modal/Modal.style.ts
  src/components/organisms/Modal/Modal.tsx
  src/lib/styles/globalStyle.ts
  src/pages/Login/Login.style.ts
  src/pages/Login/Login.tsx
Labels: feature

#37 Add width prop in Modal
  src/components/organisms/Headerbar/Headerbar.style.ts
  src/components/organisms/Modal/Modal.style.ts
  src/components/organisms/Modal/Modal.tsx
  src/components/organisms/Modal/Modal.type.ts
  src/pages/Exam/Exam.style.ts
  src/pages/Exam/Exam.tsx
  src/pages/Login/Login.tsx
Labels: feature

#40 Fixed Modal being closed by clicking another Modal
  src/components/organisms/Modal/Modal.style.ts
  src/components/organisms/Modal/Modal.tsx
Labels: feature

#42 Added Netlify redirects file
  public/_redirects
Labels: chore

#43 Create Examinee page
  src/components/atoms/Table/Table.tsx
  src/components/molecules/GlobalFilter/GlobalFilter.style.ts
  src/components/molecules/GlobalFilter/GlobalFilter.tsx
  src/components/molecules/GlobalFilter/GlobalFilter.type.ts
  src/components/molecules/GlobalFilter/index.ts
  src/components/templates/Proctor/Proctor.tsx
  src/pages/ManageExaminee/ManageExaminee.style.ts
  src/pages/ManageExaminee/ManageExaminee.tsx
  src/pages/ManageExaminee/index.ts
Labels: feature

#45 Add root route to Login page
  src/pages/Routes.tsx
Labels: feature

#48 Create Proctor page
  src/components/templates/Proctor/Proctor.tsx
  src/pages/ManageProctor/ManageProctor.style.ts
  src/pages/ManageProctor/ManageProctor.tsx
  src/pages/ManageProctor/index.ts
  src/pages/dummydata.ts
Labels: feature

#49 Add Modal in Examinee page
  src/pages/ManageExaminee/ManageExaminee.style.ts
  src/pages/ManageExaminee/ManageExaminee.tsx
Labels: feature

#51 Apply Searchbar on Header
  src/components/atoms/Input/Input.type.ts
  src/components/atoms/Table/Table.tsx
  src/components/atoms/Table/Table.type.ts
  src/components/molecules/GlobalFilter/GlobalFilter.style.ts
  src/components/molecules/GlobalFilter/GlobalFilter.tsx
  src/components/molecules/GlobalFilter/GlobalFilter.type.ts
  src/components/molecules/GlobalFilter/index.ts
  src/components/templates/FilterTable/FilterTable.style.ts
  src/components/templates/FilterTable/FilterTable.tsx
  src/components/templates/FilterTable/FilterTable.type.ts
  src/components/templates/FilterTable/index.ts
  src/pages/ManageExaminee/ManageExaminee.style.ts
  src/pages/ManageExaminee/ManageExaminee.tsx
  src/pages/ManageProctor/ManageProctor.tsx
Labels: feature

#55 Apply fonts
  src/index.tsx
  src/lib/styles/fonts/LibreBarcode128Text-Regular.ttf
  src/lib/styles/fonts/fonts.ts
  src/lib/styles/fonts/woff2/Pretendard-Black.woff2
  src/lib/styles/fonts/woff2/Pretendard-Bold.woff2
  src/lib/styles/fonts/woff2/Pretendard-ExtraBold.woff2
  src/lib/styles/fonts/woff2/Pretendard-ExtraLight.woff2
  src/lib/styles/fonts/woff2/Pretendard-Light.woff2
  src/lib/styles/fonts/woff2/Pretendard-Medium.woff2
  src/lib/styles/fonts/woff2/Pretendard-Regular.woff2
  src/lib/styles/fonts/woff2/Pretendard-SemiBold.woff2
  src/lib/styles/fonts/woff2/Pretendard-Thin.woff2
  src/lib/styles/globalStyle.ts
Labels: feature

#59 refactor: Refactoring Monitoring page
  src/components/atoms/Button/Button.type.ts
  src/components/atoms/UserList/UserList.style.ts
  src/pages/Exam/Exam.tsx
  src/pages/Monitoring/Monitoring.style.ts
  src/pages/Monitoring/Monitoring.tsx
  src/pages/Routes.tsx
Labels: refactor
